### ISSUE TITLE
Klinkang spelling should be Klinklang

### ISSUE THREAD

**Issue by jessicayyu** [ytakahashi/pokedex.js#30]
It looks like Klinkang is missing the 2nd "L" in the name. [Serebii Pokedex page.](https://www.serebii.net/pokedex-swsh/klinklang/) If you might be able to fix this in a future update, that would be wonderful. Thanks for all your hard work!

**Comment by ytakahashi** [comment]
Hi, thank you for reporting!
I fixed and published as [3.3.1](https://www.npmjs.com/package/pokedex.js/v/3.3.1).
