### ISSUE TITLE
Scarlet and Violet

### ISSUE THREAD

**Issue by jessicayyu** [ytakahashi/pokedex.js#63]
Hi, do you think you will be adding the new generation for Scarlet & Violet Pokemon later?

Thanks for your hard work, as always!

**Comment by ytakahashi** [comment]
Hi, thanks for this issue.
It's just a plan but it could be in a few month later.

**Comment by ytakahashi** [comment]
Hi @jessicayyu , I released [4.0.0](https://www.npmjs.com/package/pokedex.js/v/4.0.0) that includes Scarlet and Violet Pokemon.
Thank you for waiting.

**Comment by jessicayyu** [comment]
Awesome!!!! Thank you so much for making and maintaining this library! 🎉🎉🎉
